# Generated by Django 5.2.17 on 2026-09-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='interview_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Behavioral', 'Behavioral'), ('HR', 'HR'), ('Mixed', 'Mixed')], default='Technical', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
