# Generated by Django 5.2.17 on 2026-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0003_repair_answer_score_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
